Fix download shared photos
mib1185/py-synologydsm-api pull request #267
Opened 2023-03-09 21:18 UTC by lodesmets

Fix download shared photos: https://github.com/mib1185/py-synologydsm-api/issues/262

Shared photos need to be downloaded with FotoTeams api instead of Foto api

2023-03-15 21:10 UTC, mib1185 requested changes
Hi @lodesmets 
many thanks for bring this fix in 🤝 
I've left some comments and it would be great to have some tests for this

2023-03-15 21:10 UTC, mib1185 commented on src/synology_dsm/api/photos/model.py
> +    owner_user_id: int
i think we shoud add a bool like `is_shared` which is set to True when "owner_user_id == 0"

2023-03-15 21:10 UTC, mib1185 commented on src/synology_dsm/api/photos/__init__.py
> +            else self.THUMBNAIL_API_KEY,
we should avoid such multiline attribute associations, just set a helper variable before, like:
```python
download_api = self.THUMBNAIL_API_KEY
if item.is_shared:
    download_api = self.THUMBNAIL_FOTOTEAM_API_KEY
```

2023-03-15 21:10 UTC, mib1185 commented on src/synology_dsm/api/photos/__init__.py
> +            else self.THUMBNAIL_API_KEY,
same as above

2023-03-18 11:38 UTC, lodesmets commented
I also added a test

2023-03-18 12:14 UTC, merged