Added function to get items from the shared space
mib1185/py-synologydsm-api pull request #285
Opened 2023-05-08 18:06 UTC by lodesmets

Home assistant issue: https://github.com/home-assistant/core/issues/92600
This person used the shared space. I did some testing and found the API endpoint to get the items in the shared space

2023-05-10 16:46 UTC, lodesmets commented
> Hi @lodesmets thanks for this addition, but i've left some small comment

I made the change to the branch. lodesmets:shared_photos.

But for some reason it doesn't show up in the PR for me. 
I'm guessing a github bug. If it didn't change in a couple days, I will close this, and open a new PR

2023-05-10 18:40 UTC, mib1185 commented
not sure what was the problem, but just close and re-open solved it 😆

2023-05-10 18:49 UTC, mib1185 requested changes
Hi @lodesmets 
just one other point left, we have 3x the same code 🙈

2023-05-10 18:49 UTC, mib1185 commented on src/synology_dsm/api/photos/__init__.py
> +        return items
i think we should move this part in a separate function and reuse it in `get_items_from_album`, `get_items_from_shared_space` and `get_items_from_search`

2023-05-14 17:18 UTC, mib1185 approved these changes
LGTM, thx @lodesmets 👍

2023-05-14 17:19 UTC, merged