Add virtual machine manager
mib1185/py-synologydsm-api pull request #69
Opened 2021-11-10 11:18 UTC by realtek2017

Functionality extended to support Virtual Machine Manager API.

New methods include:

    List all Virtual Guest Names
    List Virtual Guest Statuses
    Power on a Guest
    Power off a Guest
    Shutdown a Guest

2021-11-11 19:59 UTC, mib1185 requested changes

2021-11-11 19:59 UTC, mib1185 commented on src/synology_dsm/api/virtual_machine_manager/guest.py
> +class SynoVirtualMachineManager:
this class should be moved to `__init__.py`

2021-11-11 19:59 UTC, mib1185 commented on src/synology_dsm/api/virtual_machine_manager/guest.py
> +            self._data = raw_data["data"]
you should create an own class for the guest object (_suggest `SynoVmmGuest`_) which holds all the data and exposes properties (_compare with surveillance_station_)

2021-11-11 20:02 UTC, mib1185 commented
Hi @realtek2017 
I like this idea, so let's work on it to bring it on the road 😉 

Overall please compare with the implementation of surveillance_station - it implements the generic class `SynoSurveillanceStation` which more or less represents the app itself and the class `SynoCamera` which represents the single camera instance with its properties like the name, id, model,... 
Last but not least ... tests are also needed 😉

2021-11-12 17:57 UTC, realtek2017 commented
> Hi @realtek2017 I like this idea, so let's work on it to bring it on the road wink
> 
> Overall please compare with the implementation of surveillance_station - it implements the generic class `SynoSurveillanceStation` which more or less represents the app itself and the class `SynoCamera` which represents the single camera instance with its properties like the name, id, model,... Last but not least ... tests are also needed wink
> 
> Btw I'm missing the reboot method wink

Thanks @mib1185 for all your comments, I appreciate your feedback.

My reason for adding this was driven from being able to use this eventually on the homeassistant integration :)

I will make the changes as requested, had some issues with getting poetry working so I will try and fix that for the tests.

2021-11-12 18:29 UTC, mib1185 commented
> My reason for adding this was driven from being able to use this eventually on the homeassistant integration :)

was hoping, that this is the reason behind 🤞 

> I will make the changes as requested, had some issues with getting poetry working so I will try and fix that for the tests.

If you are using VSCode and have Docker installed on your system, you can use the devcontainer in this project 😉

2024-10-04 22:08 UTC, mib1185 commented
This will be implemented with #363

2024-10-04 22:08 UTC, closed without merging